# Generated by Django 5.0.3 on 2024-03-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_studentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='student_facebook',
            new_name='student_link2',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='student_instagram',
            new_name='student_link3',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='student_telegram',
            new_name='student_link4',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='student_link1',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
